### ISSUE TITLE
[reservation_monitor:187]: Encountered a Too Many Requests error while logging in. Skipping reservation retrieval

### ISSUE THREAD

**Issue by GitterDone221** [jdholtz/auto-southwest-check-in#174]
### Version

Auto-Southwest Check-In v6.1

### Description

Script stops after encountering error 187. Running 
config.json uses "accounts" not "flights" details/credentials
machine: Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-164-generic x86_64)

Able to complete reservation from another machine running Fedora 36 using same version southwest.py script but older Chrome v. 115.0.5790.110 (Official Build) (64-bit)

### To Reproduce

run 
~/source/auto-southwest-check-in$ python3 southwest.py

### Expected Behavior

Expecting script to be able to log in, find flight(s) and go into monitoring/sleep mode, waiting to check-in

### Relevant logs and program output

```sh
<username>@<ubuntu>:~/source/auto-southwest-check-in$ python3 southwest.py --verbose
2023-10-15 17:14:50 DEBUG MainProcess[log:23]: Initialized the application
2023-10-15 17:14:50 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v6.1
2023-10-15 17:14:50 DEBUG MainProcess[main:113]: Called with 0 arguments
2023-10-15 17:14:50 DEBUG MainProcess[config:107]: Initializing configuration file
2023-10-15 17:14:50 DEBUG MainProcess[config:135]: Reading the configuration file
2023-10-15 17:14:50 DEBUG MainProcess[config:53]: Setting check fares to False
2023-10-15 17:14:50 DEBUG MainProcess[config:67]: Setting notification level to <NotificationLevel.INFO: 1>
2023-10-15 17:14:50 DEBUG MainProcess[config:80]: Using 0 notification services
2023-10-15 17:14:50 DEBUG MainProcess[config:84]: Setting retrieval interval to 24 hours
2023-10-15 17:14:50 DEBUG MainProcess[config:118]: Creating configurations for 1 accounts
2023-10-15 17:14:50 DEBUG MainProcess[main:142]: Monitoring 1 accounts and 0 reservations
2023-10-15 17:14:51 DEBUG Process-1[reservation_monitor:154]: Acquiring lock...
2023-10-15 17:14:51 DEBUG Process-1[reservation_monitor:156]: Lock acquired
2023-10-15 17:14:51 DEBUG Process-1[reservation_monitor:178]: Retrieving reservations for account
2023-10-15 17:14:51 DEBUG Process-1[webdriver:124]: Starting webdriver for current session
2023-10-15 17:14:51 DEBUG Process-1[webdriver:135]: Loading Southwest Check-In page
2023-10-15 17:14:57 DEBUG Process-1[webdriver:79]: Logging into account to get a list of reservations and valid headers
2023-10-15 17:14:59 DEBUG Process-1[webdriver:164]: Waiting for headers_set to be set
2023-10-15 17:14:59 DEBUG Process-1[webdriver:168]: headers_set set successfully
2023-10-15 17:14:59 DEBUG Process-1[webdriver:164]: Waiting for login_request_id to be set
2023-10-15 17:14:59 DEBUG Process-1[webdriver:156]: Login response has been received
2023-10-15 17:14:59 DEBUG Process-1[webdriver:168]: login_request_id set successfully
2023-10-15 17:15:00 DEBUG Process-1[webdriver:179]: Logging in failed for an unknown reason
2023-10-15 17:15:00 WARNING Process-1[reservation_monitor:187]: Encountered a Too Many Requests error while logging in. Skipping reservation retrieval
2023-10-15 17:15:00 DEBUG Process-1[reservation_monitor:167]: Lock released
2023-10-15 17:15:00 DEBUG Process-1[reservation_monitor:116]: Sleeping for 86391 seconds
```

**Comment by jdholtz** [comment]
Hey. This may be because of a Chrome version mismatch, which was fixed in the develop branch. Could you try it on that branch and see if it works? Just run `git pull && git checkout develop`

**Comment by GitterDone221** [comment]
I just ran  "git pull && git checkout develop" (2x) and reran southwest.py. Looks like error #187 still not gone.

Here is the log:

=========================

<username>@<ubuntu>:~/source/auto-southwest-check-in$ git pull && git checkout develop
Already up to date.
Already on 'develop'
Your branch is up to date with 'origin/develop'.
<username>@<ubuntu>:~/source/auto-southwest-check-in$ python3 southwest.py --verbose
2023-10-15 19:16:00 DEBUG MainProcess[log:23]: Initialized the application
2023-10-15 19:16:00 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v6.1
2023-10-15 19:16:00 DEBUG MainProcess[main:113]: Called with 0 arguments
2023-10-15 19:16:01 DEBUG MainProcess[config:107]: Initializing configuration file
2023-10-15 19:16:01 DEBUG MainProcess[config:135]: Reading the configuration file
2023-10-15 19:16:01 DEBUG MainProcess[config:53]: Setting check fares to False
2023-10-15 19:16:01 DEBUG MainProcess[config:67]: Setting notification level to <NotificationLevel.INFO: 1>
2023-10-15 19:16:01 DEBUG MainProcess[config:80]: Using 0 notification services
2023-10-15 19:16:01 DEBUG MainProcess[config:84]: Setting retrieval interval to 24 hours
2023-10-15 19:16:01 DEBUG MainProcess[config:118]: Creating configurations for 1 accounts
2023-10-15 19:16:01 DEBUG MainProcess[main:142]: Monitoring 1 accounts and 0 reservations
2023-10-15 19:16:01 DEBUG Process-1[reservation_monitor:154]: Acquiring lock...
2023-10-15 19:16:01 DEBUG Process-1[reservation_monitor:156]: Lock acquired
2023-10-15 19:16:01 DEBUG Process-1[reservation_monitor:178]: Retrieving reservations for account
2023-10-15 19:16:01 DEBUG Process-1[webdriver:103]: Starting webdriver for current session
2023-10-15 19:16:02 DEBUG Process-1[webdriver:115]: Loading Southwest Check-In page
2023-10-15 19:16:09 DEBUG Process-1[webdriver:79]: Logging into account to get a list of reservations and valid headers
2023-10-15 19:16:11 DEBUG Process-1[webdriver:144]: Waiting for headers_set to be set
2023-10-15 19:16:11 DEBUG Process-1[webdriver:148]: headers_set set successfully
2023-10-15 19:16:11 DEBUG Process-1[webdriver:144]: Waiting for login_request_id to be set
2023-10-15 19:16:12 DEBUG Process-1[webdriver:136]: Login response has been received
2023-10-15 19:16:12 DEBUG Process-1[webdriver:148]: login_request_id set successfully
2023-10-15 19:16:12 DEBUG Process-1[webdriver:185]: Logging in failed for an unknown reason
2023-10-15 19:16:12 WARNING Process-1[reservation_monitor:187]: Encountered a Too Many Requests error while logging in. Skipping reservation retrieval
2023-10-15 19:16:12 DEBUG Process-1[reservation_monitor:167]: Lock released
2023-10-15 19:16:12 DEBUG Process-1[reservation_monitor:116]: Sleeping for 86388 seconds
=========================

**Comment by jdholtz** [comment]
What Chrome version are you running? Also, I forgot to mention that you need to run `pip install -r requirements.txt` after checking out the develop branch as I updated the dependencies.

**Comment by jdholtz** [comment]
Hey @GitterDone221, any update to my comment above?

**Comment by jdholtz** [comment]
@cmclinton do past versions work for you?

**Comment by cmclinton** [comment]
I just reverted to 5.1 by git checkout 314fcb1. I then ran pip install -r requirements.txt and checked python3 southwest.py --version. It reported 5.1. I then ran southwest.py with username and password. I immediately received a "too many requests" error.

**Comment by GitterDone221** [comment]
> Hey @GitterDone221, any update to my comment above?

Running "pip install -r requirements.txt" has resolved the issue for me.
I am running Google Chrome 118.0.5993.70

**Comment by jdholtz** [comment]
> Running "pip install -r requirements.txt" has resolved the issue for me.

Good to know. It may have just been a mismatch between the driver/browser versions which was fixed in the develop branch. Thanks for testing.

> Something worth noting

Interesting. Thanks for detailing how to fix this issue if someone runs into it.

> I immediately received a "too many requests" error.

@cmclinton Have you ever had it work on this machine before? I'm not familiar with AWS, but Southwest may be detecting common IPs (data centers) and your AWS instance could be one of those IPs that they block. However, that may only be true if this script has never worked on that machine before.

**Comment by jdholtz** [comment]
Hey @cmclinton, any updates to my previous comment?

**Comment by cmclinton** [comment]
The script did not work correctly on AWS. It logged in and fetched my reservation, but it never checked me in. This is just speculation, but if AWS is idling servers or something along those lines, then maybe using "sleep (seconds)" doesn't work.

To recap my recent experience with the script:

- AWS - runs and gets reservations, but never checked me in
- WSL at work - SSL error probably due to network configuration
- WSL at home (different computer than work) - timeout on web driver - ticket #176
- Windows 11 at home - worked to check me in, but then it did not check me in for the return trip. Haven't filed a ticket on this.

**Comment by jdholtz** [comment]
> This is just speculation, but if AWS is idling servers or something along those lines, then maybe using "sleep (seconds)" doesn't work.

I found[this](https://stackoverflow.com/questions/72530406/aws-batch-job-failing-with-python-time-sleep-over-70-seconds) , so you can check to make sure you don’t have it configured to go to sleep. That would be strange behavior if there wasn’t a way to run scripts that sleep for long periods of time. 

Did the last lines of the logs just say “Sleeping for XXXX seconds…”?

**Comment by jdholtz** [comment]
@cmclinton are you still having all of the issues described above (excluding #176)?
